#!/bin/sh

set -ev

./tools/bazel build //...
./tools/bazel build --platforms=//:rpi-armv7-clang //...
./tools/bazel build --config=crosstool //...
./tools/bazel build --config=crosstool --cpu=armeabihf //...

./tools/bazel build --platforms=//:rpi-armv7-clang --enable_bzlmod --lockfile_mode=off //...
